### ISSUE TITLE
Compatibility with Mod Triumph: Remote swallows minecraft:inventory_changed 

### ISSUE THREAD

**Issue by BuggaNoia** [Lothrazar/Storage-Network#105]
As long as the Advanced Storage Remote is in the player inventory event minecraft:inventory_changed never reached the triumph mod. Therefore archivements depending on it get never triggered.

ModPack: SevTech Ages 3.0.8

What happens: Crafting an item (GalacticCraft Compressor), but don't get the archievement for this.
What is expected: Get the archivement in the moment the item is in the player inventory
Work Around: Take the remote out of your inventory (put it into a chest) and pick up again the triggering item.

**Comment by Lothrazar** [comment]
I just testied again and im getting the achievements, also chatted a bit with sevtech & triumph devs, looks ok.
