### ISSUE TITLE
NBT data not respected when selecting a recipe for the Storage Request Table from NEI

### ISSUE THREAD

**Issue by Cabu** [Lothrazar/Storage-Network#111]
When crafting IC2 copper cables, the Storage Request Table, pick most of the time (not always) some Insulated Copper Cable in place of a Copper Cable. I think the difference between the 2 types of cable is defined in the NBT fields.
JEI and not NEI (I still old school :-D)

**Comment by PrinceOfAmber** [comment]
Yep looks like an issue. IN contrast the regular crafting table just greys out the + button since you do not have materials 
![nbt crafting issue](https://user-images.githubusercontent.com/621529/46998273-ed713c00-d0d6-11e8-9b95-19992b60b0ea.gif)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2659393
