### ISSUE TITLE
Colossal Chests Compatibility 1.5.2

### ISSUE THREAD

**Issue by ClockwerkKaiser** [Lothrazar/Storage-Network#118]
Minecraft version & Mod Version:
1.12.2 - 1.5.2

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
The Network no longer recognizes Colossal Chests when attached. The same exact setup (a simple network consisting of only one colossal chest) was working fine on v1.4.0. When I rolled back to that version, everything was working fine again. 

Crash log (if any):
No crash.

**Comment by PrinceOfAmber** [comment]
Thanks for the report, i didnt think anything had changed with the normal connection cables.

**Comment by PrinceOfAmber** [comment]
I think you have to connect it ONLY to the "Collossal Chest Core" block, it wont connect to any other part. I recorded a gif https://www.screentogif.com/    linked below   

https://imgur.com/OhM0PKV
