### ISSUE TITLE
Attaching then attempting to use Storage Request Table to Network causes a crash

### ISSUE THREAD

**Issue by GeorgeWL** [Lothrazar/Storage-Network#124]
Minecraft version & Mod Version:
Mc 1.12.2, Mod 1.2.9

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
I attached the storage network to some chests, then attached the master, then attached the storage request table. On trying to open the Storage Request UI, minecraft crashed out

Crash log (if any):

https://paste.dimdev.org/kaniyelege.mccrash
(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Thanks for the report, there used to be this issue with tooltips but its fixed in the latest version 1.5.4
