### ISSUE TITLE
1.5.4 priority was reversed on storage link cable

### ISSUE THREAD

**Issue by frog9394** [Lothrazar/Storage-Network#125]
Minecraft version & Mod Version:
Minecraft verisons 1.12.2 & Mod Version 1.5.4 (Mod Pack version: World of Dragon 13.7.129)

Single player or Server:
Single player and Server the same

Describe problem (what you were doing / what happened):
I have found that the priority setting for storage link cable was reversed on the new version because my storage system was mess up after I updated the mod Pack. Before was larger number first and now it reversed and not match with the UI instruction (The priority up and priority down button). Please check. Thanks!

**Comment by Lothrazar** [comment]
hey sorry for the delay in responding.  Can you give a precise example or a build/screenshot of anetwork . there was a change in previous versions reltaed to this , and coming soon ill update some of the tooltips to be more clear .

**Comment by Lothrazar** [comment]
Looks like this is working as intended, ihave one chest at 0, one chest at 3

items go into the = 0 one first, since smaller goes first. tooltips in english updated to match   https://minecraft.curseforge.com/projects/simple-storage-network/files/2659393
