### ISSUE TITLE
Duplication bug with exu2

### ISSUE THREAD

**Issue by Pival81** [Lothrazar/Storage-Network#126]
Minecraft version & Mod Version:
1.12.2, SimpleStorageNetwork-1.12.2-1.5.4.jar, extrautils2-1.12-1.9.8.jar

Single player or Server:
Single player, but I think it would apply on servers too.

Describe problem (what you were doing / what happened):
I attached a player chest to the network and didn't set any access in the chest.
When I went to take out of the system a stack of a block, it duplicated it, without taking it from my inventory. I think it's similar to #55 where the system forcefully takes items from ghost slots.

**Comment by Lothrazar** [comment]
I tried and failed this a few times so i have to just add a blacklist to dis-allow this block from connecting to the network

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2660404
