### ISSUE TITLE
Duplication Bug When Used With Real Filing Cabinet

### ISSUE THREAD

**Issue by remclave** [Lothrazar/Storage-Network#127]
Minecraft version & Mod Version:
      Minecraft: 1.12.2
      Mod: 1.5.4

Single player or Server:
      Server

Describe problem (what you were doing / what happened):
      I take items out, say 12 redstone in File Folder. 12 redstone remain and 12 in hand. Place in personal inventory and repeat. 

Crash log (if any): 
      NO crash log.

      Images:
![2018-12-14_15 51 34](https://user-images.githubusercontent.com/31051239/50029827-bfff1c80-ffb9-11e8-825b-3ea49b595995.png)
![2018-12-14_15 51 42](https://user-images.githubusercontent.com/31051239/50029829-c392a380-ffb9-11e8-920d-700c5a5bbe09.png)

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Thanks for the report!


Question:   Do you have FastWorkbench installed?  this affects how things are done in some places (or a full modlist from latest.log or something) https://minecraft.curseforge.com/projects/fastworkbench

**Comment by TacticalUniverse** [comment]
@Lothrazar yes Fastworkbench is installed in the pack

**Comment by remclave** [comment]
I have removed FastWorkbench from a copy of the modpack and the issue is still there when tested in single player. However, I have also confirmed that the issue is NOT with Simple Storage Network. It is with Real Filing Cabinet. 

Thank your for your assistance Lothrazar.

**Comment by remclave** [comment]
This issue is closed.
