### ISSUE TITLE
Suggestion: Cross Compatibility with ae2 and/or refined Storage

### ISSUE THREAD

**Issue by AnimalLover567** [Lothrazar/Storage-Network#133]
I would like to suggest Cross Compatibility with ae2 and/or refined Storage, I know it's a strange request but my packs have both ae2 and refined, just a crazy suggestion.

**Comment by Lothrazar** [comment]
I do have plans for an addon mod for this. 


Since 1.6.0 there has been an API using capabilities  so anyone could make one in theory

**Comment by Lothrazar** [comment]
Closed as duplicate of https://github.com/Lothrazar/Storage-Network/issues/72
