### ISSUE TITLE
Crafting recipes that use planks

### ISSUE THREAD

**Issue by kragnoth** [Lothrazar/Storage-Network#139]
1.12.2 minecraft
any forge that is compatible
SimpleStorageNetwork-1.12.2-1.6.6.jar 

Any recipe that uses planks will only work if you have vanilla planks in the storage inventories.

Every other oredict works fine. The plank one only works if you have oak planks.

I'll try to get a log when I get home.  Should have a list of other mods, might be a conflict somewhere random as Darkosto tested this (though I don't remember it working for non-oak planks... )

edit: getting the same thing for logs as well.  Going to try disabling crafting tweaks and fastworkbench and report back if it persists.  What type of info would be helpful for figuring this out?

**Comment by majijn** [comment]
im pretty sure what happens with oredict recipes is that it tries to use the first entry in the oredict only, for planks that would indeed be oak planks.

**Comment by Lothrazar** [comment]
Do you have fastworkbench installed, that might make a difference.

Without it this is what happens for me, chests from spruce planks   made using https://screentogif.com 
![chest with planks](https://user-images.githubusercontent.com/621529/56434770-e3e5ae00-628a-11e9-8fa6-211ec847d532.gif)
