### ISSUE TITLE
trying to pick up a searched for renamed item, picks up the first available item of that type.

### ISSUE THREAD

**Issue by majijn** [Lothrazar/Storage-Network#140]
Describe problem (what you were doing / what happened):
renaming for example a crate , then trying to search for it , only shows up if I search to what I renamed it to, however, when I try to grab it, it gives me the empty ones which are in the same inventory, but earlier than the renamed crate

![2019-04-06_01 31 36](https://user-images.githubusercontent.com/18368034/55661854-e4079780-580e-11e9-8501-bb3c4a1f9fca.png)
![2019-04-06_01 31 39](https://user-images.githubusercontent.com/18368034/55661855-e4a02e00-580e-11e9-9b05-f7194d4c969d.png)
![2019-04-06_01 31 41](https://user-images.githubusercontent.com/18368034/55661856-e4a02e00-580e-11e9-9b9f-e2a09dafb60d.png)
![2019-04-06_01 31 43](https://user-images.githubusercontent.com/18368034/55661857-e4a02e00-580e-11e9-8fc0-12262bffc6b9.png)

**Comment by Lothrazar** [comment]
Hmm. yeah its searching on the rename, but grabbing items doesnt consider that.

**Comment by Revvilo** [comment]
This is a nightmare to deal with when trying to get out things like Enchanted Books or Analyzed Silents Gems because of all the subtle differences in NBT 😆

**Comment by Lothrazar** [comment]
old stale version, removing for cleanup.  reopen for any issues that come up with new issue template
