### ISSUE TITLE
Chest movers get voided on a full inventory

### ISSUE THREAD

**Issue by Elrol** [Lothrazar/Storage-Network#143]
Minecraft version & Mod Version: 1.12.2-1.5.7

Single player or Server: Server

Describe problem (what you were doing / what happened):
Not sure how to explain it other then just listing what I did and the outcome.

1) Filled gold chests with items
2) Used iron chest movers on the gold chests
3) put the chest  movers inside a gold chest that was connected to the simple storage network
4) attempted to take out some of the chest movers with gold chests in them, while my inventory was full

Outcome: The ones pulled out while my inventory was full were deleted completly

Crash log (if any): N/A

**Comment by Lothrazar** [comment]
is Iron chest movers from this mod? https://minecraft.curseforge.com/projects/chest-transporter

**Comment by Elrol** [comment]
Yep thats the one. And the chests were from the metal chest mod

**Comment by Lothrazar** [comment]
other mod hasnt updated since 2018, issue reported on stale version of SSN 1.5.7. closing for cleanup, reopen any new issues with new template if they occur in modpacks etc
