### ISSUE TITLE
Unexpected crash when loading an old world

### ISSUE THREAD

**Issue by ZRunner** [Lothrazar/Storage-Network#145]
Minecraft version & Mod Version: **MC** 1.12.2 **| Mod** 1.7.2 **| Forge** 1.12.2-14.23.5.2823
Single player mode

*Describe problem (what you were doing / what happened):* Just opening an "old" world (opened the last time 3 weeks ago), and my games crashes immediatly. I don't have the time to do anything, it just crashes. The map was created and played with the 1.5.7 version of the mod before today. Everything works fine when opening a new world, so it seems to be only a problem of backwards compatibility :/

Crash log: [here](https://paste.dimdev.org/vumiriduve.mccrash)

**Comment by Lothrazar** [comment]
Fixed it latest release
