### ISSUE TITLE
UI background Request

### ISSUE THREAD

**Issue by Norsered** [Lothrazar/Storage-Network#146]
Minecraft version & Mod Version: 1.12

As a future feature, can the background UI be changed from the dark grey background to a brighter color?
Or can an option be placed within the storagenetwork.cfg to change the background color and text color to brighten up the display?

**Comment by Lothrazar** [comment]
I am currently happy with the look and feel.

However you or Anyone can easily make a resource pack to change this.  Several packs including soartex have redone the GUI and many blocks.  

<3 

check out assets/storagenetwork/textures/gui/request.png
