### ISSUE TITLE
Server stalling

### ISSUE THREAD

**Issue by ApolloMCC** [Lothrazar/Storage-Network#147]
Minecraft version & Mod Version: 1.12 ,  1.7.2

Single player or Server: Server

Describe problem (what you were doing / what happened): Server kick everyone out and stalling forever until you kill it. 

Crash log (if any): Here's the stall report: https://pastebin.com/3D4ccqrK , https://pastebin.com/AUStBwGt

I have banned the whole mod for now because i do not know which item does this.

**Comment by Lothrazar** [comment]
The log is acting like its filling a recipe into a crafting grid, but this shouldnt happen when the world is loading.

I can add some saftey checks and catches to avoid the crash but the root cause

**Comment by ApolloMCC** [comment]
Ok so do you think it's safe to unban the mod?

**Comment by Lothrazar** [comment]
Latest release has a patch to handle it, but i didnt actually narrow down root cause as i think some other mod is related.  

If you can do it safely can you bring it back with new version

**Comment by Lothrazar** [comment]
This issue looks resolved, open a new issue please for anything else https://minecraft.curseforge.com/projects/simple-storage-network/files/2703012
