### ISSUE TITLE
Stock upgrade not working??

### ISSUE THREAD

**Issue by kohlth** [Lothrazar/Storage-Network#149]
Minecraft version & Mod Version: 1.12.2 , 1.7.2   skyfactory 4 

Single player or Server: Server, skyfactory 4 

Describe problem (what you were doing / what happened): I was trying to use the stock upgrade (in a export cable) to have only a stack of sky orchards resin and acorns in a packager, it did not work, i have tried a chest and it does not seem to work either and keeps acting like a regular export cable without a stock upgrade.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by kobini2** [comment]
Got the same issue, on the same pack, with 1.7.3.
The problem more is, we can't change anything in the stock upgrade (or there is no way to know how to set it up).

**Comment by xGHOSTFREAKx** [comment]
To point it out like this better, the stock upgrade seems to not work with sky factory 4, it doesnt let you choose how many items you want to be in the exported storage, i'll test this mod in a normal 1.12.2 world without any other mods, maybe its an issue with only sf4 and maybe some other modpacks, i'll post a reply again if it still has the same issue

**Comment by xGHOSTFREAKx** [comment]
okay, tested in a brand new world in single player, 1.7.2 and 1.7.3, still doesnt let you select / place the amount (max amount) of items which should be in the extracted storage, before stopping to export the items, just exports them as normal when its in the filter list, and it exports everything out of the system, i'll check the processing cables, maybe they are now supposed to handle this? if they are meant to, let everyone know on the bug fixes list @Lothrazar

**Comment by xGHOSTFREAKx** [comment]
https://github.com/Darkosto/SkyFactory4Issues/issues/541 better discription if needed

**Comment by Lothrazar** [comment]
Yeah it should look like this when working, where it shows the stack number and you can change it


![fixdisplay](https://user-images.githubusercontent.com/621529/56634842-4b4b8700-6618-11e9-90f2-476eddc659de.PNG)

**Comment by BrianEdmonds** [comment]
How sure are you of your fix? I just upgraded to SkyFactory 4.0.3, which has SSN 1.7.4, and I'm now seeing numbered stacks in the exporter's inventory, but it still exports every acorn into my assemblicator.

**Comment by BrianEdmonds** [comment]
Actually, it looks like it's specifically the Mekanism assemblicators. I switched to Cyclic packagers, and the exporters with stock upgrades work as expected there.

**Comment by xGHOSTFREAKx** [comment]
thanks for the fix, i went through the files as a start but haven't gotten far cause of family stuff, thought i'd return today but u've already done it, lol, thanks, i made a comment in the code where you can add 2 more else if's, but its gonna change a bit cause you gonna need to add a paramater for shift button too, so if you want you can change it, its working though so doesn't matter if you wanna add or not :) have fun though. ima go on with my c# course for now :)

**Comment by Lothrazar** [comment]
This issue looks resolved, open a new issue please for anything else https://minecraft.curseforge.com/projects/simple-storage-network/files/2703012

**Comment by Keridos** [comment]
This is still happening for me in SF4, v.1.7.8 of simple storage network.
Turns out this is in Compact machines. I can attach a crafting terminal through the tunnels but apparently something weird happens with cables, they do not attach visually though the working terminal would suggest it partially works. export buses on the other side of the network (behind the tunnel) show the bugged stock behavior. Would love to see this issue being fixed.
