### ISSUE TITLE
Question on suggestions?

### ISSUE THREAD

**Issue by kohlth** [Lothrazar/Storage-Network#150]
I love the idea of this mod, storage network without complications, no complicated setups, no 5 years of crafting , no stupid cable and drive storage limits, no large ugly complicated multi-blocks , just a simple, clean, 
storage network that can outdo most storage networks on the simple things.

my question is though... what is the main focus for the mod, what are the set limitations. 
i ask because i have a lot of ideas but dont know if they would be good or fitting for the mod its self 

for example, i would really like a block to store things in the mod for storing a lot of items and avoiding the million chests , maybe something that doesn't need a external storage connector and is a multi-block, or maybe it has upgrades, or maybe you add storage with chests and a material cost.

getting off topic a bit there but in a gist, i have a lot of ideas but dont know if they are il fitting for the mod

anyways i cant wait for your reply so i can start getting ideas out of my head and onto github

**Comment by majijn** [comment]
use immersive engineering multiblock silos or https://minecraft.curseforge.com/projects/storage-cabinet's are my recommendation to you in the meantime. @kohlth

**Comment by kohlth** [comment]
i was asking what sort of suggestions are good for the mod and what are not fitting types of suggestions.

But i thank you for that, the storage cabinets look interesting

**Comment by Lothrazar** [comment]
storage cabinets are compatible. any new suggestions are welcome in a new issue
