### ISSUE TITLE
Export/Import cable filter needs NBT/Metadata match function - suggestion

### ISSUE THREAD

**Issue by shikyo13** [Lothrazar/Storage-Network#151]
**Minecraft version & Mod Version:**

1.12.2
1.7.3

**Single player or Server:**

Single

**Describe problem (what you were doing / what happened):**

Export cable attached to simple culinary generator, and set to supply Bacon from Tcon starts putting slimes into the generator because they are both oredict to Tcon:edible .

**Comment by Lothrazar** [comment]
I cannot replicate this bug.

 When i check the "NBT" box is checked its correctly filtering enchanted items for me

**Comment by shikyo13** [comment]
Apologies, I had somehow completely overlooked the checkboxes on the import/export cables due to the different positioning. I only saw them on the processing cables. I actually had to go back and look 2x to confirm that I was mistaken. Thanks for the response!
