### ISSUE TITLE
[Suggestion]: Automation: crafting, smelting, and placing and breaking

### ISSUE THREAD

**Issue by kohlth** [Lothrazar/Storage-Network#152]
Simple storage network is cool and all but it lacks things other storage mods have: automation
sure there is the automation node thing but it only works if there are machines to output to, and sometimes those machines are limited, laggy, or possibly dont work well with the mod. 

my suggestion: lag friendly simple storage networks automation machines
(P.S: the cyclic packager is a bit laggy)

**Auto crafting**

one recipe per autocrafter

has option to stop crafting if the amount of a item reaches over, under, or equal to a set amount

Instead of crafting one craft really fast, it crafts multiple crafts every few seconds, at base it crafts 2 crafts every 5 seconds with one speed upgrade lowers time by one. stack upgrade increases amount of crafts done by 2 (not multiplied) 

(maybe it doesn't use speed upgrades and max stack upgrades will make it craft 128 crafts every 5 seconds??)

will attempt to craft even if it doesn't have the materials to craft the maximum amount craft able
(will craft one craft if there isn't enough for 2 crafts and so on)

connects directly to network

(config option to use fuel and use fuel restocking upgrade?)

(restock upgrade will have a filter on what fuel it will use from the system)

**Auto smelter**

has two smelting slots

will attempt to smelt 

stack upgrades increase the amount of smelting slots in it
speed increases furnace speed (divides time by 1.5 each upgrade current time so full speed gives a smelting time of 2 seconds)

efficiency upgrade, multiplys fuel burn time by 1.25 each upgrade

connects directly to network

has option to stop smelting if the amount of a item reaches over, under, or equal to a set amount

**Breaker and placer**

breaker: requires pickaxe, breaks block and puts it into the system, will attempt to break every 5 seconds

placer: places block(s) set to place, has some placement options, will attempt to place every 5 seconds 

both require fuel by default but can be turned off in the config

(P.S: the cyclic packager is a bit laggy)

**Comment by Lothrazar** [comment]
out of scope for the mod, keeping it simple.  tons of other mods do this already and they can just plug in
