### ISSUE TITLE
Servercrash by shiftclicking upgrades into importcable

### ISSUE THREAD

**Issue by VoxelVixen** [Lothrazar/Storage-Network#153]
Minecraft version & Mod Version: 1.12.2 - 1.7.3 

Single player or Server: Server with Skyfactory 4 v4.0.2

Describe problem (what you were doing / what happened): A player shiftclicked a stack of speed upgrades into a import cable , resulting in a server crash. 
His area became unusable as the server would crash again if somebody came close enough so i had to rollback the server.

Crash log (if any): https://pastebin.com/Wcftqq2N

**Comment by Lothrazar** [comment]
Oops somehow it got into a divide-by-zero situation.  Updating to use Math.max(___, 1) so speed will never be zero

**Comment by Lothrazar** [comment]
This issue looks resolved, open a new issue please for anything else https://minecraft.curseforge.com/projects/simple-storage-network/files/2703012
