### ISSUE TITLE
Collision AABB's are off..

### ISSUE THREAD

**Issue by LezChap** [Lothrazar/Storage-Network#154]
Minecraft version & Mod Version:
On version 1.7.3 in SF 4.0.2.

Single player or Server:
SSP

Describe problem (what you were doing / what happened):
The collision boxes when multiple cables are adjacent aren't aligned.  Compared to another mod you do, Cyclic:
![Storage Network Cable Example](https://imgur.com/hN01K2x.jpg) (notice I'm interacting with the cable).
![Cyclic Pipes Example](https://imgur.com/eqW0yTW.jpg) (I can see/interact with the wooden slab through the hole in the pipes.)

Pretty sure this is a miscalculation in the AABB for the collision boxs.  Fixing this miscalculation in the AABB would allow you to reach around dense cable systems and to the TEs you can see behind them.

Edit to note:  This impacts all cables I've tested with.

**Comment by Lothrazar** [comment]
Hey this is a nice find.

With cyclic cables. you do get the extra Corner AABB thing , but ONLY when you mouse over the center. you can still click through it since it disappears.

**Comment by LezChap** [comment]
To be honest, I like the code for the AABB's in Cyclic better than the code for them in this mod...it's looks so much cleaner and more elegant. :)

**Comment by Lothrazar** [comment]
Yeah they still could be better , ill take another look in 163
