### ISSUE TITLE
Item loss bug when using the request table.

### ISSUE THREAD

**Issue by darkhax** [Lothrazar/Storage-Network#155]
Minecraft version & Mod Version: 1.12.2-1.7.2
Single player or Server: Server
Describe problem (what you were doing / what happened): I was trying to craft a storage crate from BDSM using Iron blocks. Another player tried to craft some amber at the same time. The items that were in the grid for the storage crate were completely voided and replaced with the amber items. The ingredients for my crafting recipe are completely gone, and were not dropped in the world.
Crash log (if any): No log info

**Comment by Lothrazar** [comment]
This one will be fun to test :)

**Comment by Lothrazar** [comment]
adding a call to a "clearContainerRecipe" where the packet sets the recipe, which does the same thing as 'clear the recipe' button and puts things in the network.

**Comment by OGTEnzoHD** [comment]
same issue still there on SMP on 1.7.4

**Comment by nifker** [comment]
can approve this too on v1.12.2

**Comment by Lothrazar** [comment]
Yep still happening on 1.7.4 will take another look
