### ISSUE TITLE
Suggestion:  Have Import Cables default to Blacklist

### ISSUE THREAD

**Issue by LezChap** [Lothrazar/Storage-Network#156]
Minecraft version & Mod Version:
On version 1.7.3 in SF 4.0.2.

Currently, Import Cables default to whitelist.  In my opinion, this is counter-intuitive, and they should default to blacklist mode and import everything when placed in the world, and then if I want to restrict them later, I can.  This would also mirror the way most import/transport devices in other mods work.

**Comment by Lothrazar** [comment]
But if it defaults to blacklist. that means as soon as i place it down, it will start sucking items in like a free for all before I get a chance to open the GUI and customize it

So really, stariting in whitelist is a way to start it paused until you set it up . 

That is the logic anyway, i will think about it and look at what other mods do

**Comment by LezChap** [comment]
That logic makes sense now that it's brought forward...I guess I'm just used to how other mods (like AE and Refined Storage) work.
