### ISSUE TITLE
Unable to open UI

### ISSUE THREAD

**Issue by XBoulder** [Lothrazar/Storage-Network#157]
Minecraft: 1.12.2
Mod: 1.7.4 (modified Sky Factory 4)

Single player 

With the newest Mod-version, the UI doesn't show up anymore when using either the Storage Remote or the Storage Request Table. Switching back to 1.7.3 will show up the UI. Tried it also in a complete new world with new generated blocks and items with the same result.

**Comment by kobini2** [comment]
Error log: [pastebin](https://pastebin.com/QHXMmUdW)

**Comment by kobini2** [comment]
This can be closed.
This was due to an outdated FastWorkbench version.
