### ISSUE TITLE
Crash when rotating cable with Crescent Hammer.

### ISSUE THREAD

**Issue by Jamjardavies** [Lothrazar/Storage-Network#158]
Crash on this line when trying to use the crescent hammer on cables.

Note: This is on a server, and the crash is client-side, and used in the mod-pack Sky Factory 4.

https://github.com/Lothrazar/Storage-Network/blob/fbbf8892aa5accbeee577cc85070a53c50df6933/src/main/java/mrriegel/storagenetwork/block/cable/TileCableWithFacing.java#L77

Error looks like a missing null-check from getTileMaster which can return a null.

Crash log: https://pastebin.com/DSEwZKby

**Comment by hugoprudente** [comment]
I just faced this bug playing the SkyFactory 4.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
