### ISSUE TITLE
When taking things from other storage systems, it will not decrease in other systems.

### ISSUE THREAD

**Issue by Leaveleaf** [Lothrazar/Storage-Network#159]
When taking things from other storage systems, it will not decrease in other systems.
My English is not very good, I took some pictures
![image](https://user-images.githubusercontent.com/19620848/56728844-57eded80-6786-11e9-9ffe-09140437e8d8.png)
![image](https://user-images.githubusercontent.com/19620848/56728923-88358c00-6786-11e9-91db-c3992ed38c5b.png)

**Comment by Lothrazar** [comment]
For reference https://github.com/Lothrazar/Storage-Network/blob/develop/src/main/java/mrriegel/storagenetwork/capabilities/CapabilityConnectableLink.java#L167

**Comment by Lothrazar** [comment]
I cant replicate this with other mods, can you also post it here https://github.com/CyclopsMC/IntegratedDynamics ?

Its possible that mod has to update, or possibly both of us?
