### ISSUE TITLE
Storage Link Cable filter import does not read from Charset Barrels

### ISSUE THREAD

**Issue by Sixdd6** [Lothrazar/Storage-Network#160]
### Minecraft version & Mod Version:
Minecraft 1.12.2 
forge buld 2836
mod version 1.7.4

### Single player or Server:
Server

### Describe problem (what you were doing / what happened):
When adding a storage link cable to a charset barrel the cables' filter import button does not read what is in the barrel.

### Crash log (if any):
No crash/No log

**Comment by Lothrazar** [comment]
This is a bug with Charset Barrels. 

They need to implement IItemHandler getSlots and/or getStackInSlot , refer them to my CapabilityConnectableLink.java
