### ISSUE TITLE
Storage Link Cable import filter slots are not mapped correctly

### ISSUE THREAD

**Issue by Sixdd6** [Lothrazar/Storage-Network#161]
### Minecraft version & Mod Version:
Minecraft 1.12.2
forge buld 2836
mod version 1.7.4

### Single player or Server:
Server

### Describe problem (what you were doing / what happened):
When placing items manually into the slots of the filter area the slots are mapped wrongly. For example, placing an item into the first slot of the filter works fine, placing an item into the second slot will map the third slot to that item, placing an item into the third slot will map to the fifth slot, and it carries on that way till you get to the second row of slots. On the second row of slots the first slot maps to the second slot of the first row, the second slot of the second row maps to the fourth slot of the first row and so on.

### Crash log (if any):
No crash/No log

**Comment by RainerZufahl** [comment]
I encountered the same issue, here is a gif to visualise:

![2019-05-17_00-26-06](https://user-images.githubusercontent.com/18621898/57891191-cc262900-783a-11e9-9d44-fa17a1910565.gif)

The issue is also present in single player.

**Comment by Vordyn** [comment]
Same here, in Sky Factory 4 (4.0.5) [mod version 1.7.4]  single player. Additionally, shift clicking items into the list would be Greatly appreciated.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
