### ISSUE TITLE
Walkthrough cables

### ISSUE THREAD

**Issue by theawfullwaffle** [Lothrazar/Storage-Network#163]
SkyFactory 4 v4.0.3
Minecraft v1.12.2
Simple Storage Network v1.7.4
Single player

I was placing cable to setup a network and walked through the cables. Not sure if this is related to Issue #154 but it is possible to walk through the "space" between the center of the blocks that connected cables occupy (encircled in the image below).

![SimpleStorageCollision](https://user-images.githubusercontent.com/37811968/56871643-b0272880-69ee-11e9-9ffb-2588165f56d1.jpg)

**Comment by RainerZufahl** [comment]
I've encountered this issue as well, with multiple connected Link Cables. Here is a gif of me walking through the cables:

https://imgur.com/nCuA3Hs

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
