### ISSUE TITLE
Crash When Clicking Storage Request Table

### ISSUE THREAD

**Issue by marikc0** [Lothrazar/Storage-Network#164]
Minecraft version & Mod Version:
MC 1.12.2 - Mod 1.7.4

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
Clicked the Storage Request Table with only a Storage Network Master and a few cables attached with export cables to Storage Drawers (mod)

Crash log (if any):
https://paste.dimdev.org/ohasolihig.mccrash

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

Note: 1.7.3 does not crash in the same way, so I downgraded.

**Comment by Lothrazar** [comment]
Old version of fastbench. Yep, going back to 1.7.3 makes sense, thats fine. 

In 1.7.4 if you you use it you need a minimum of FastWorkBench 1.7.0

Thanks for the report :)
