### ISSUE TITLE
Blacklist in config doesn't work

### ISSUE THREAD

**Issue by Yorkforce** [Lothrazar/Storage-Network#166]
Minecraft version & Mod Version:
1.12/1.7.4

Single player or Server:
Server

Describe problem (what you were doing / what happened):
With the entry:
```
    # Disable these blocks from ever being able to connect to the network, they will be treated as a non-inventory. [default: [extrautils2:playerchest]]
    S:BlacklistBlocks <
        extrautils2:playerchest
        tconstruct:tooltables
        tconstruct:toolforge
     >
```
The tool forge and and tool tables can still connect to the network.

Crash log (if any):
N/A

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
