### ISSUE TITLE
Unable to connect to CompactStorage

### ISSUE THREAD

**Issue by robertstepp** [Lothrazar/Storage-Network#167]
Minecraft version & Mod Version:
1.12.2/1.7.4

Single player or Server:
Both

Describe problem (what you were doing / what happened):
I am attempting to connect a compact storage chest to a simple storage network but it will not work. I have had it work on SkyFactory but can not get it to work on a custom modpack.

Crash log (if any):
Doesn't crash

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by DoctorVortex** [comment]
im having the same problem

**Comment by curiosity-a** [comment]
Have you tried adding ComPatchedStorage mod to see if that fixes it?

**Comment by robertstepp** [comment]
That did work. Thanks.
