### ISSUE TITLE
Duplication with Storage remotes

### ISSUE THREAD

**Issue by dreeadnought** [Lothrazar/Storage-Network#169]
Minecraft version & Mod Version: Minecraft 1.12.2 Mod Version 1.7.4

Single player or Server: Single and Server

Describe the problem (what you were doing / what happened):
Items are duplicating on any remote that has a crafting grid.  When items are placed into the crafting grid either by JEI or manual placement and shift-left-clicking on the produced item the item remains in the crafting grid and one is added to the storage system.  Either removing and replacing an ingredient, Shift-clicking from JEI or closing and opening the remote resets the duplication allowing it to be repeated.  

Crash log (if any):

I created a separate network with 64 Redstone and 64 sticks  took half and placed in crafting grid
![Before](https://user-images.githubusercontent.com/37687658/57174798-0c2beb80-6df9-11e9-9ef9-8f604bd22ff2.PNG)
As seen here there is no reduction in material, but a Redstone Torch has been made. 
![After](https://user-images.githubusercontent.com/37687658/57174814-35e51280-6df9-11e9-9542-597479817d5e.PNG)

Here is a list of mods currently installed:

Just Enough Items (JEI) (by mezz)
ConnectedTexturesMod (by tterrag1098)
Login Shield (by Glasspelican)
In Control! (by McJty)
Thermal Dynamics (by TeamCoFH)
Ender Storage 1.8.+ (by covers1624)
Chameleon (by jaquadro)
MTLib (by jaredlll08)
Pam's Simply Strawberries (by MatrexsVigil)
Zoo & Wild Animals Rebuilt : ZAWA (by Soggy_Mustache)
Storage Drawers (by jaquadro)
MrCrayfish's Furniture Mod (by Mr_Crayfish)
Bad Wither No Cookie - Reloaded (by kreezxil)
Hammer (Lib) Core (by Zeitheron)
Cucumber Library (by BlakeBr0)
Gravestone mod - Graves (by NightKosh)
[SBM] Elevators (by darkguardsman)
Initial Inventory (by jaredlll08)
Waystones (by BlayTheNinth)
BiblioCraft (by JDSinclair)
Good Ol' Currency (by BeardlessBrady)
Nether Living (by Terrails)
Mob Control Wands (by Micmux)
Oreberries (by josephcsible)
Simple Storage Network (by Lothrazar)
Sonar Core (by Ollie_Lansdell)
Ferdinand's Flowers (by c0_0ry)
LLibrary (by iLexiconn)
Custom Main Menu (by lumien231)
Wings (by pau101)
V-Tweaks (by oitsjustjose)
Flux Networks (by Ollie_Lansdell)
Chisel (by tterrag1098)
Canny Composter (by JasonSpangler)
MrCrayfish's Jumping Castle Mod (by Mr_Crayfish)
Water Strainer (by Rubironi)
Building Gadgets (by direwolf20)
Natural Fauna Mod: a ZAWA addon (by Mnesikos)
Resource Loader (by lumien231)
Bird's Foods (by no_space)
TheDragonLib (by sokratis12GR)
JourneyMap (by techbrew)
Guidebook (by gigaherz)
Doggy Talents (by Percivalalb)
CraftTweaker (by jaredlll08)
Familiar Fauna (by Glitchfiend)
Redstone Flux (by TeamCoFH)
Pillar (by Vazkii)
CodeChicken Lib 1.8.+ (by covers1624)
Thermal Foundation (by TeamCoFH)
Plants (by Shadows_of_Fire)
Delivery (by lemonszz)
Exotic Birds (by Pavoreality)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Storage Cabinet (by AshIndigo)
CoFH Core (by TeamCoFH)
Cooking for Blockheads (by BlayTheNinth)
Thermal Expansion (by TeamCoFH)
Quark (by Vazkii)
Stygian End: Biome Expansion (by super_fluke50036)
Biome Paint Tools (by Zeitheron)
Novam Terram (by The_Kipster)
Bookworm (by Soggy_Mustache)
Aquaculture (by Shadowclaimer)
Inventory Sorter (by cpw11)
CoFH World (by TeamCoFH)
Better Than Mending (by legobmw99)
CreativeCore (by CreativeMD)
Veining (by LalalaStab)
LittleTiles (by CreativeMD)
Repurpose (by WuestMan)
Comforts (by theillusivec4)
AutoRegLib (by Vazkii)
Zoocraft Discoveries (by Pavoreality)
Cyclic (by Lothrazar)
TerraCore (by Terrails)
Villager Trade Tables (by csb987)
Better Animals Plus (by Cybercat5555)
Item Scroller (by masa_)
BetterFps (by Guichaguri)
Fence Overhaul (by The_WeatherPony)
CoralReef (by primetoxinz)
Waddles (by Girafi)
ArmorPlus (by sokratis12GR)
TorchMaster (by xalcon)
Controlling (by jaredlll08)
Hwyla (by TehNut)
Wumple Util Library (by JasonSpangler)
More Overlays (by feldim2425)
Placebo (by Shadows_of_Fire)

**Comment by agrinder** [comment]
Bump

**Comment by Lothrazar** [comment]
I feel like im not doing this right.  You said " shift-left-clicking on the produced item", but all that does is craft 64 of them.

All i did was make the 32 and 32 setup like you did. and shift left click is that right?

I have forge 2768, SSN 1.7.4, 

![shift left click](https://user-images.githubusercontent.com/621529/58388996-df738a00-7fda-11e9-9f3a-3879ed43adfb.gif)

**Comment by Lothrazar** [comment]
Nevermind im dumb, previous comment was in the table. 

Also bug does not happen if FastWorkbench is installed (such as skyfactory4) but with that removed i see it

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
