### ISSUE TITLE
Storage Request Table does not remember the state of JEI search toggle

### ISSUE THREAD

**Issue by curiosity-a** [Lothrazar/Storage-Network#172]
Minecraft version & Mod Version:
Minecraft 1.12
SimpleStorageNetwork-1.12.2-1.7.4

Single player or Server:
Single player

Describe problem (what you were doing / what happened):
1. Open Storage Request Table
2. Turn off JEI search
3. Restart the game
4. Open Storage Request Table
5. Observe the bug

**Comment by Protheus** [comment]
if possible add a config to have JEI search in SSN disabled.

**Comment by curiosity-a** [comment]
> if possible add a config to have JEI search in SSN disabled.

Note that this won't fix the bug.

**Comment by Lothrazar** [comment]
Yes, currently the red-green flag is stored per client, but only in local memory and is not saved on disc anywhere.

The upside is that if you set one table to red, all tables get it.  And the setting is for you only, if other players use that table it wont change for them.

The downside is that yes its not saved. 

I should save it with the player data somehow.  Or the tile entity / remote item stack.

**Comment by Lothrazar** [comment]
its too late in 1.12 lifespan to make a breaking change like this. modpacks and what people are used to, etc. marking as 1.16+ to consider
