### ISSUE TITLE
Facades - Request

### ISSUE THREAD

**Issue by Caldico** [Lothrazar/Storage-Network#174]
Hi, this has most likely been requested before but I think Facades would be an amazing feature to the mod. 

Thats it really, i think it would make the mod just that bit better (can't get much better). As an idea for a recipe, it could be like the other cables where it has 4 storage cables and a block in the middle, maybe glass?

**Comment by Lothrazar** [comment]
This is a very very large undertaking, using forge multiblocks and i have no idea how they work.  

If someone wants to make an external addon mod, i will do what i can to support that 100%  and they can message me , but its not something i have time or interest in right now.  

Sorry it is a really cool feature  i know.
