### ISSUE TITLE
Interaction between SSN and Cyclic is allowing duping of items

### ISSUE THREAD

**Issue by JackRuby1** [Lothrazar/Storage-Network#175]
Minecraft version & Mod Version:
1.12.2
1.12.2-1.7.4 SSN
1.12.2-1.19.8 Cyclic
Single player or Server:
All?

Describe problem (what you were doing / what happened):
Using simple storage network link cable attached to a Cyclic Auto Crafter, Items aren't pulled from the crafter instead they are duplicated. This can be either items in the input queue or the crafting slots.

Crash log (if any):

Here's the issue over on SkyFactory Issue tracker: https://github.com/Darkosto/SkyFactory4Issues/issues/601

**Comment by Lothrazar** [comment]
Nice find. this could happen with any modded block that has restricted slots, such as slots that dont work with hoppers.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files/2716372
