### ISSUE TITLE
Storage Export Cable exports cocoa beans instead of lapis lazuli

### ISSUE THREAD

**Issue by malaclypse2** [Lothrazar/Storage-Network#176]
Minecraft version & Mod Version: MC version 1.12.2, mod version 1.7.4

Single player or Server: Single player

Describe problem (what you were doing / what happened):
I have a Storage Export Cable with Stock Upgrade pointing into an Auto Crafter (from the Cyclic mod, version 1.19.8).  The Export Cable is set to export one stack each of Gold Ingots, Iron Ingots, Lapis Lazuli and Clay.  

The Export Cable properly stocks the iron, gold, and clay, but instead of lapis lazuli it outputs cocoa beans, and does not stop at a single stack.  Instead, it fills the whole machine with cocoa beans.  It does not seem to matter how I have the checkboxes for "OreDict", "Meta" or "NBT" on the export cable. Cocoa Beans and Lapis Lazuli are both ore dictionaried as "dye" (in addition to some other things).

Crash log (if any):
None

**Comment by malaclypse2** [comment]
Addendum: If I lower the priority on the Link Cable attached to my Lapis storage to be lower than the one attached to my Cocoa Bean stores, then the Export Cable will export Lapis Lazuli instead of Cocoa beans.  I think that demonstrates that the export cable is pulling items based on the ore dictionary, no matter what is set on the "OreDict" setting of the export cable.

**Comment by curiosity-a** [comment]
It likely has nothing to do with ore dictionary. All vanilla dyes are the same ID.

**Comment by Lothrazar** [comment]
Metadata checkbox will solve this.  

But actually it should be checked by default to make it easier for everyone  so ill make that tiny 
![meta](https://user-images.githubusercontent.com/621529/58531192-5608b700-8196-11e9-9178-6a6f307a6c8e.PNG)
change
