### ISSUE TITLE
Storage Request Table

### ISSUE THREAD

**Issue by ConcernedLoli** [Lothrazar/Storage-Network#177]
Minecraft version & Mod Version:
1.12.2 and 1.7.4

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Logged into the server after the mod(pack) being updated, and right clicking on the Storage Request Table does nothing; breaking and replacing it doesnt work either.

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
If the Master tile is in an unloaded chunk, or disconnected, it will not open.  

If those things are all resolved, icant replicate this exactly.  Could be  related to this which is a recent fix https://github.com/Lothrazar/Storage-Network/issues/141

**Comment by Salnex** [comment]
https://paste.dimdev.org/zowaxexule.mccrash is a paste of the errors thrown reproducing this.
Attached is a screenshot of the setup producing this error.

![2019-06-03_21 49 46](https://user-images.githubusercontent.com/26846378/58799802-9f9b4b00-8649-11e9-96a4-a5b22fb8a2a2.png)

**Comment by Salnex** [comment]
This error is can be replicated in 1.7.6 https://paste.dimdev.org/ivijobiqiz.mccrash

**Comment by Salnex** [comment]
Issue is with fastworkbench 1.6.1 installed. Updating fastworkbench, or changing the storagenetwork.cfg to B:allowFastWorkBenchIntegration=false fixes in all in 1.7.6 and 1.7.4 of storagenetwork
