### ISSUE TITLE
Cable Hitboxes

### ISSUE THREAD

**Issue by CoolDCB** [Lothrazar/Storage-Network#180]
Minecraft version & Mod Version: Minecraft 1.12 (I am unsure of the mod version, I am playing SkyFactory 4)

Single player or Server: Single Player

Describe problem (what you were doing / what happened): The Simple Storage cable hitboxes take up the whole box meaning if you go up close to a importer or exporter and try to interact with another block it will open the cable GUI. Also when trying to break a block on the other side of the cable the blocks hitbox blocks you and starts breaking the cable.

MORE: Another glitch with the Simple Storage Cables is that when you stand on them they cause a glitch where the hitbox glitches the player around.

**Comment by RainerZufahl** [comment]
I've seen this issue as well, it has to be one of the 1.7.x versions if I'm not mistaken. You can go into your Menu > Mods and look for the Simple Storage Network mod to find out the exact version you're using.

**Comment by Jkosio23** [comment]
Its 1.7.4 at least where I'm getting the same issue!

**Comment by Jkosio23** [comment]
[This Commit](https://github.com/Lothrazar/Storage-Network/commit/f628c3cb0ee8aed9e2fc23dc1ca22a13b65df0df)

**Comment by Lothrazar** [comment]
I made a slight change in 1.7.5, but i think its still happening.

Is the bug still the same or better or worse? I might jus revert that whole commit

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files
