### ISSUE TITLE
Shift Right Click hangs program

### ISSUE THREAD

**Issue by robobeaver6** [Lothrazar/Storage-Network#182]
Minecraft version & Mod Version:
Skyfactory 4 
SimpleStorageNetwork-1.12.2-1.7.4.jar

Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
When in the processing cable menu interface, shift right clicking an inventory item causes the system to hang.  Shutting the application is the only option.  No logs appear to be generated in the console window

Crash log (if any):
No log that I can see.

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files
