### ISSUE TITLE
duplication glitch with tinker's construct's crafting station

### ISSUE THREAD

**Issue by malthespil** [Lothrazar/Storage-Network#183]
Minecraft version: 1.12.2
Mod Version: 1.12.2-1.7.4
mod pack: sky factory 4
mod pack launcher:  AT launcher
tinker's construct mod version: 1.12.2-2.12.0.135

Single player or Server: single player

Describe problem (what you were doing / what happened):
1. connect tinker's construct's crafting station with storage network
2. put item into the crafting station
3. open storage request table, storage remote or simple storage remote and take the item into your inventory. 
item isn't removed from menu or crafting station so is now duplicated.

Crash log (if any): none

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
Fixed in 1.7.5  same cause as https://github.com/Lothrazar/Storage-Network/issues/175

Or if i missed something let me know
