### ISSUE TITLE
Storage Remote Eats Items

### ISSUE THREAD

**Issue by ZSFshmN** [Lothrazar/Storage-Network#184]
Minecraft version & Mod Version:
Minecraft version: 1.12.2
Mod version: 1.7.4
Single player or Server:
Single Player

Describe problem (what you were doing / what happened):
When using the storage remote (the one with crafting) and you click it in your inventory while its gui is open, and items in the crafting grid will be deleted and not just dropped on the ground

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by Lothrazar** [comment]
When i click the remote , it doesnt even close anything, nothing even happens.  I cant seem to replicate this 


Do you have a mod list? Maybe you can record a GIF or something? 

![184](https://user-images.githubusercontent.com/621529/58687754-6015eb80-8337-11e9-960e-7c6906038da9.gif)
