### ISSUE TITLE
JEI load recipe into crafting grid doesn't work with tools that take damage

### ISSUE THREAD

**Issue by dakamojo** [Lothrazar/Storage-Network#185]
Minecraft version & Mod Version: 1.12.2-1.7.4

I'm using this mod with GregTech that has a lot of crafting recipes that utilize tools that take damage.  Other mods use the same mechanic.  If I use JEI and shift-click a recipe to load it into the crafting grid, everything loads fine.  Except the tool will only load if it is undamaged.  I remember that AE2 had this problem initially and then made a change to enable using the damaged tool.

**Comment by Lothrazar** [comment]
Yep this is an issue with some recipes, ill check this out. 
![185](https://user-images.githubusercontent.com/621529/58713088-bb1b0300-8376-11e9-9a03-becafc8ab5e8.gif)

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files
