### ISSUE TITLE
issues with storage request table/mod

### ISSUE THREAD

**Issue by Batosi001** [Lothrazar/Storage-Network#186]
Minecraft version & Mod Version:
Galacticraft 1.12.2

Single player or Server:
server

Describe problem (what you were doing / what happened): issues with storage request table, dupping items, not transfering to craft glitching stuck until broken

Crash log (if any):
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-05-27 01:29:54 EDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1087)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3941)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IndexOutOfBoundsException: Index: 45, Size: 45
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.inventory.Container.getSlot(Container.java:120)
    at net.minecraft.inventory.Container.setAll(Container.java:527)
    at net.minecraft.client.network.NetHandlerPlayClient.handleWindowItems(NetHandlerPlayClient.java:1191)
    at net.minecraft.network.play.server.SPacketWindowItems.processPacket(SourceFile:50)
    at net.minecraft.network.play.server.SPacketWindowItems.processPacket(SourceFile:12)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2620794424 bytes (2499 MB) / 8355053568 bytes (7968 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 127 mods loaded, 127 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                      | Version                  | Source                                             | Signature                                |
       |:------ |:----------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | UCHIJA | minecraft               | 1.12.2                   | minecraft.jar                                      | None                                     |
       | UCHIJA | mcp                     | 9.42                     | minecraft.jar                                      | None                                     |
       | UCHIJA | FML                     | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | forge                   | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJA | micdoodlecore           |                          | minecraft.jar                                      | None                                     |
       | UCHIJA | openmodscore            | 0.12.1                   | minecraft.jar                                      | None                                     |
       | UCHIJA | foamfixcore             | 7.7.4                    | minecraft.jar                                      | None                                     |
       | UCHIJA | randompatches           | 1.12.2-1.11.0.3          | randompatches-1.12.2-1.11.0.3.jar                  | None                                     |
       | UCHIJA | itemblacklist           | 1.4.0                    | ItemBlacklist-1.4.0.jar                            | None                                     |
       | UCHIJA | actuallyadditions       | 1.12.2-r144              | ActuallyAdditions-1.12.2-r144.jar                  | None                                     |
       | UCHIJA | baubles                 | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | UCHIJA | actuallybaubles         | 1.1                      | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
       | UCHIJA | ic2                     | 2.8.106-ex112            | industrialcraft-2-2.8.106-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
       | UCHIJA | advanced_solar_panels   | 4.3.0                    | Advanced Solar Panels-4.3.0.jar                    | None                                     |
       | UCHIJA | ctm                     | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | UCHIJA | appliedenergistics2     | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | UCHIJA | endercore               | 1.12.2-0.5.57            | EnderCore-1.12.2-0.5.57.jar                        | None                                     |
       | UCHIJA | jei                     | 4.14.1.234               | jei_1.12.2-4.14.1.234.jar                          | None                                     |
       | UCHIJA | codechickenlib          | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | redstoneflux            | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | cofhcore                | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar             | None                                     |
       | UCHIJA | brandonscore            | 2.4.10                   | BrandonsCore-1.12.2-2.4.10.198-universal.jar       | None                                     |
       | UCHIJA | cofhworld               | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | thermalfoundation       | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | draconicevolution       | 2.3.21                   | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |
       | UCHIJA | thermalexpansion        | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | enderio                 | 5.0.44                   | EnderIO-base-1.12.2-5.0.44.jar                     | None                                     |
       | UCHIJA | mantle                  | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                           | None                                     |
       | UCHIJA | chisel                  | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | UCHIJA | tconstruct              | 1.12.2-2.11.0.106        | TConstruct-1.12.2-2.11.0.106.jar                   | None                                     |
       | UCHIJA | p455w0rdslib            | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                     | None                                     |
       | UCHIJA | ae2wtlib                | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                          | None                                     |
       | UCHIJA | galacticraftcore        | 4.0.2.190                | GalacticraftCore-1.12.2-4.0.2.190.jar              | None                                     |
       | UCHIJA | galacticraftplanets     | 4.0.2.190                | Galacticraft-Planets-1.12.2-4.0.2.190.jar          | None                                     |
       | UCHIJA | asmodeuscore            | 0.0.6                    | AsmodeusCore-1.12.2-0.0.6.jar                      | None                                     |
       | UCHIJA | betterboilers           | master-1.1.31            | BetterBoilers-1.1.1.jar                            | None                                     |
       | UCHIJA | betterbuilderswands     | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | UCHIJA | blockcraftery           | 1.12.2-1.1.0             | Blockcraftery-Mod-1.12.2.jar                       | None                                     |
       | UCHIJA | buildcraftlib           | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftcore          | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftbuilders      | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcrafttransport     | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftsilicon       | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | crafttweaker            | 4.1.13                   | CraftTweaker2-1.12-4.1.13.jar                      | None                                     |
       | UCHIJA | theoneprobe             | 1.4.25                   | theoneprobe-1.12-1.4.25.jar                        | None                                     |
       | UCHIJA | buildcraftcompat        | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftenergy        | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftfactory       | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | buildcraftrobotics      | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                       | None                                     |
       | UCHIJA | chancecubes             | 1.12.2-4.0.0.271         | ChanceCubes-1.12.2-4.0.0.271.jar                   | None                                     |
       | UCHIJA | chickenchunks           | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | classiccombat           | 1.0.0                    | ClassicCombat-1.12-1.0.0.jar                       | None                                     |
       | UCHIJA | cyclopscore             | 1.3.0                    | CyclopsCore-1.12.2-1.3.0.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCHIJA | colossalchests          | 1.7.2                    | ColossalChests-1.12.2-1.7.2.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | UCHIJA | computercraft           | 1.80pr1                  | ComputerCraft1.80pr1.jar                           | None                                     |
       | UCHIJA | conarm                  | 1.2.2                    | conarm-1.12.2-1.2.2.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJA | ctgui                   | 1.0.0                    | CraftTweaker2-1.12-4.1.13.jar                      | None                                     |
       | UCHIJA | crafttweakerjei         | 2.0.2                    | CraftTweaker2-1.12-4.1.13.jar                      | None                                     |
       | UCHIJA | custommainmenu          | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                  | None                                     |
       | UCHIJA | customnpcs              | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
       | UCHIJA | customstuff4            | 0.5.3                    | customstuff4-1.12.2-0.5.3.jar                      | None                                     |
       | UCHIJA | cyclicmagic             | 1.19.9                   | Cyclic-1.12.2-1.19.9.jar                           | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | UCHIJA | enderiobase             | 5.0.44                   | EnderIO-base-1.12.2-5.0.44.jar                     | None                                     |
       | UCHIJA | enderioconduits         | 5.0.44                   | EnderIO-conduits-1.12.2-5.0.44.jar                 | None                                     |
       | UCHIJA | enderiopowertools       | 5.0.44                   | EnderIO-conduits-1.12.2-5.0.44.jar                 | None                                     |
       | UCHIJA | enderioendergy          | 5.0.44                   | EnderIO-endergy-1.12.2-5.0.44.jar                  | None                                     |
       | UCHIJA | enderiomachines         | 5.0.44                   | EnderIO-machines-1.12.2-5.0.44.jar                 | None                                     |
       | UCHIJA | enderstorage            | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UCHIJA | forgelin                | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
       | UCHIJA | exnihilocreatio         | 1.12.2-0.4               | exnihilocreatio-1.12.2-0.4.jar                     | None                                     |
       | UCHIJA | extracells              | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                       | None                                     |
       | UCHIJA | mjrlegendslib           | 1.12.2-1.1.8             | MJRLegendsLib-1.12.2-1.1.8.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
       | UCHIJA | extraplanets            | 1.12.2-0.5.2             | ExtraPlanets-1.12.2-0.5.2.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
       | UCHIJA | extrautils2             | 1.0                      | extrautils2-1.12-1.9.8.jar                         | None                                     |
       | UCHIJA | zerocore                | 1.12-0.1.2.3             | zerocore-1.12-0.1.2.3.jar                          | None                                     |
       | UCHIJA | bigreactors             | 1.12.2-0.4.5.50          | ExtremeReactors-1.12.2-0.4.5.50.jar                | None                                     |
       | UCHIJA | foamfix                 | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                          | None                                     |
       | UCHIJA | galaxyspace             | 2.0.6                    | GalaxySpace-1.12.2-2.0.6.jar                       | None                                     |
       | UCHIJA | guideapi                | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
       | UCHIJA | icbmclassic             | 1.12.2-3.3.0.63          | ICBM-classic-1.12.2-3.3.0b63.jar                   | None                                     |
       | UCHIJA | mekanism                | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
       | UCHIJA | teslacorelib            | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJA | industrialforegoing     | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.8-232.jar          | None                                     |
       | UCHIJA | inventorytweaks         | 1.64+dev.144.88fda94     | InventoryTweaks-1.64+dev.144.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJA | ironchest               | 1.12.2-7.0.54.838        | ironchest-1.12.2-7.0.54.838.jar                    | None                                     |
       | UCHIJA | journeymap              | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
       | UCHIJA | jaff                    | 1.7_for_1.12             | Just-a-Few-Fish-Mod-1.12.jar                       | None                                     |
       | UCHIJA | justenoughreactors      | 1.1.1.47                 | JustEnoughReactors-1.12.2-1.1.1.47.jar             | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
       | UCHIJA | laggoggles              | SPONGEFORGE-1.12.2-4.1   | LagGoggles-SPONGEFORGE-1.12.2-4.1.jar              | None                                     |
       | UCHIJA | lootbags                | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                        | None                                     |
       | UCHIJA | malisiscore             | 1.12.2-6.4.1-SNAPSHOT    | malisiscore-1.12.2-6.4.1-SNAPSHOT.jar              | None                                     |
       | UCHIJA | malisisadvert           | 1.12.2-6.1.0             | malisisadvert-1.12.2-6.1.0.jar                     | None                                     |
       | UCHIJA | malisisblocks           | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                     | None                                     |
       | UCHIJA | malisisdoors            | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | UCHIJA | mcjtylib_ng             | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                            | None                                     |
       | UCHIJA | mekanismgenerators      | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
       | UCHIJA | mekanismtools           | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
       | UCHIJA | modularforcefieldsystem | 3.0.1                    | MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar               | None                                     |
       | UCHIJA | numina                  | 1.10.0                   | ModularPowersuits-1.12.2-0.7.0.25.jar              | None                                     |
       | UCHIJA | powersuits              | 1.12.2-0.7.0.25          | ModularPowersuits-1.12.2-0.7.0.25.jar              | None                                     |
       | UCHIJA | mousetweaks             | 2.9                      | MouseTweaks-2.9-mc1.12.2.jar                       | None                                     |
       | UCHIJA | natura                  | 1.12.2-4.3.2.62          | Natura-Mod-1.12.2.jar                              | None                                     |
       | UCHIJA | nuclearcraft            | 2.12k                    | NuclearCraft-2.12k--1.12.2.jar                     | None                                     |
       | UCHIJA | omlib                   | 3.0.1-162                | omlib-1.12.2-3.0.1-162.jar                         | None                                     |
       | UCHIJA | ompd                    | 3.0.0-36                 | ompd-1.12.2-3.0.0-36.jar                           | None                                     |
       | UCHIJA | openmods                | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJA | openblocks              | 1.8                      | OpenBlocks-1.12.2-1.8.jar                          | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UCHIJA | openmodularturrets      | 3.0.1-264                | openmodularturrets-1.12.2-3.0.1-264.jar            | None                                     |
       | UCHIJA | randomthings            | 4.2.4                    | RandomThings-MC1.12.2-4.2.4.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJA | reborncore              | 3.13.0.400               | RebornCore-1.12.2-3.13.0.400-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | UCHIJA | redstonearsenal         | 2.6.1                    | RedstoneArsenal-1.12.2-2.6.1.15-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | resourceloader          | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UCHIJA | rftools                 | 7.61                     | rftools-1.12-7.61.jar                              | None                                     |
       | UCHIJA | sgcraft                 | 1.13.2                   | SGCraft-1.3-mc1.12.2.jar                           | None                                     |
       | UCHIJA | storagenetwork          | 1.7.4                    | SimpleStorageNetwork-1.12.2-1.7.4.jar              | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | UCHIJA | thermaldynamics         | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UCHIJA | simplyjetpacks          | 2.2.10.63                | SimplyJetpacks2-1.12.2-2.2.10.63.jar               | None                                     |
       | UCHIJA | sonarcore               | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                     | None                                     |
       | UCHIJA | tinker_io               | rw2.7.1                  | tinker_io-1.12.2-rw2.7.1.jar                       | None                                     |
       | UCHIJA | tinkertoolleveling      | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | UCHIJA | vanillafix              | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | UCHIJA | veinminer               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | UCHIJA | veinminermodsupport     | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar              | None                                     |
       | UCHIJA | wanionlib               | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                           | None                                     |
       | UCHIJA | wct                     | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar        | None                                     |
       | UCHIJA | mysticallib             | 1.12.2-1.0.0             | MysticalLib-1.12.2.jar                             | None                                     |
       | UCHIJA | teslacorelib_registries | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.11.0.3.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.144.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.1-SNAPSHOT.jar)
                                        
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.13.0.400
              Runtime Debofucsation 1
              RenderEngine: 0
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Unknown

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)
any and all help would be greatly appreciated as this mod is definetly the best out there for this!

**Comment by Lothrazar** [comment]
Thanks for the report
"dupping items"
How? when?  what did you do to set this up? Its a crash log, im not sure how a crash makes dupes

"not transfering to craft glitching stuck until broken" Im not sure what this means, I ASSUME the transfer part means JEI.  but i have no idea.  When i use JEI it looks like this, no issues
![186](https://user-images.githubusercontent.com/621529/58712822-303a0880-8376-11e9-9293-e3371f85257f.gif)

**Comment by Lothrazar** [comment]
Also those two issues aside, what were you doing when the crash happened? I spam clicked and every squiare inch of the GUI and couldnt find a crash. 

Also nowhere in the log does it mention simplestorage. So if the crash is from here i dont know where or why or how it happens. 

Can you do something like this


"Before the crash i had this setup _____
Then i did exactly these steps _______
Then it crashed exactly when i did this one thing___
"
