### ISSUE TITLE
Inventory shift/Gui issue 

### ISSUE THREAD

**Issue by NINAustinFett** [Lothrazar/Storage-Network#187]
Minecraft version & Mod Version:
1.12.2. Mod Version 1.7.5 

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Every time I open the Storage request table every item in my inventory gets shifted over 1 slot to the right. I have tried many versions of forge as well as the mod. I have downloaded the world off the server and there is no issue on the same world in single player or on the server in creative. Any help is appreciated 

  
![2019-05-31_11 36 02](https://user-images.githubusercontent.com/51243875/58730824-6c875c00-83aa-11e9-993a-3c0805877826.png)
![2019-05-31_11 36 43](https://user-images.githubusercontent.com/51243875/58730838-71e4a680-83aa-11e9-9692-2e29f69fbb69.png)

Modlist All in latest stable versions and with default configs
Agricraft
antique atlas
appleskin
Backpacks
Buables
bibliocraft
biomesOplenty
cavern
ChiselAndBits
ftb utilities
iron chests
jei 
megaloot
optifne
simple storage networks

**Comment by Lothrazar** [comment]
I think its the same as this https://github.com/Lothrazar/Storage-Network/issues/179

Thanks for the mod list . 100% does not happen  whenever i test it with no other mods installed, so trying to look for a mod conflict

**Comment by Lothrazar** [comment]
See 179 thread for updates
