### ISSUE TITLE
NULL being stored in *.nbt causes SpongeForge to shutdown server.

### ISSUE THREAD

**Issue by Wissi** [Lothrazar/Storage-Network#188]
**Minecraft version & Mod Version:**
Minecraft 1.12.2 
SimpleStorageNetwork Mod Versions:  1.12.2-1.6.0 thru 1.7.5
(Tested all of them individually. Only prior versions will work. So issue might be in 1.6.0)
(Using prior versions will not cause this and server is fine.)
Forge ver. 2825
SpongeForge ver. 2825-7.1.6-RC3741

**Single player or Server:**
Server side only.

**Describe problem (what you were doing / what happened):**
Server with SpongeForge is shutdown due to:
``NULL being stored in *.nbt`` 
``Sponge is forcing a shutdown of the game because someone is storing nulls in an NBTTagCompound. Our implementation and Minecraft's strictly prevents this from happening, however, certain mods are not null checking. Please provide this report in a report to the associated mod!``
``Potential Culprit: storagenetwork``
``NBT Key: stack Exception!``

**Crash log (if any):**
[Crash](https://gist.github.com/Wissi/db951e0ca914e216fdbc869019dd6dce) 

If you need the full log let me know.

Thanks.

**Comment by Lothrazar** [comment]
Dang why is spongeforge so picky. Saying nulls are not allowed when minecraft and forge and every other mod is happy with them. <3 

I mean its an easy fix for me to make, but still

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/simple-storage-network/files
