### ISSUE TITLE
Using a wrench on a Storage Link Cable crashes game.

### ISSUE THREAD

**Issue by AaronAsAChimp** [Lothrazar/Storage-Network#189]
Minecraft version & Mod Version:
1.12.2 - 1.7.5

Single player or Server:
Server

Describe problem (what you were doing / what happened):
When using a wrench (crescent hammer) to rotate a cable the client crashed, the server did not.

Crash log (if any):

[crash-2019-06-02_21.23.34-client.txt](https://github.com/Lothrazar/Storage-Network/files/3245501/crash-2019-06-02_21.23.34-client.txt)

**Comment by Lothrazar** [comment]
Thanks for the report, was fixed in latest versions

**Comment by Lothrazar** [comment]
https://github.com/Lothrazar/Storage-Network/issues/158
