### ISSUE TITLE
unsafe inventory handling

### ISSUE THREAD

**Issue by CreepyCre** [Lothrazar/Storage-Network#190]
Minecraft version & Mod Version:
Minecraft 1.12.2 & SpongeForge
Mod Version 1.7.4 (& custom version with the #179 fix as well)

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Upon trying to implement the fix for #179 into a custom version that would be compatible with 1.7.4 (I thought it was handled server-side) I encountered something peculiar. The slots were still shifting, so it seemed to me that the ContainerRequest is handled client-side.

As seen in one of the replies to #179 one of the crafting table slots shifts into the player inventory. If you put an item in that slot (far top-left of the player inventory) while in the terminal the slot will get correctly saved to the terminal (as it is in the craften area) if you leave the interface. When you now open your inventory, close it again and then re-open the interface the item in the crafting table will overwrite the first slot in you inventory, so after leaving the interface it will now be in your inventory and in the interface. This allows for duplication of any item.

Although this is a minor problem as most people wont be able to compile a version with such a cheat (and those who could probably wouldn't) I still think you should work on fixing this, as in any web based programming the user should always be assumed to have malicious intent.

Thanks for taking the time to read my suggestion

**Comment by Lothrazar** [comment]
So following these steps
- If you put an item in that slot (far top-left of the player inventory) while in the terminal
- . When you now open your inventory, close it again and then re-open the interface 

The dupe looks fixed in 1.7.7
