### ISSUE TITLE
Not able to click full stacks with left or shift left click from system, gives a random number depending on what the item is.

### ISSUE THREAD

**Issue by JackRuby1** [Lothrazar/Storage-Network#191]
Minecraft version & Mod Version:
1.12.2
SimpleStorageNetwork-1.12.2-1.7.5.jar	
Pack SF4 406

Single player or Server:
Server

Describe problem (what you were doing / what happened):
Not able to click full stacks with left or shift left click from system, gives a random number depending on what the item is.
https://i.imgur.com/1GUEakw.gifv

Crash log (if any):

(If this is a suggestion and not a bug report, delete all this and just write your suggestion!)

**Comment by JackRuby1** [comment]
Side note, the set up is a compact chest connected with a storage link.

**Comment by SoulK1ller** [comment]
Also having this problem, set up with simple storage network and real filing cabinets. SF4, 406.

**Comment by SirOlaf** [comment]
I don't think the amount is random. It seems to be the amount of storage slots the item occupies. So if you split your item into 64 slots, you could technically get a full stack.

**Comment by Lothrazar** [comment]
I think this was fixed in 176 or 177 and i jus forgot to update the issue
