### ISSUE TITLE
Golden Lasso

### ISSUE THREAD

**Issue by red360** [Lothrazar/Storage-Network#63]
Crafting golden lassos do not require XP.

**Comment by PrinceOfAmber** [comment]
Thanks for your patience i couldnt respond right away

Looks like Golden lasso from EXu2 registers its recipe as a vanilla recipe type.  So of course storage network sees that and works with it.

Non vanilla recipes are things like custom Solderer from RS or furnace recipes.  so to me it SEEMS like its on the other mods end to fix?  

Speaking of RS i guess I can test if their system crafts it

**Comment by PrinceOfAmber** [comment]
Note to self: Source code for that items recipe
https://github.com/rwtema/Extra-Utilities-2-Source/blob/846a0a59f603c4a60f02d3a6fedc4e468e4ea229/1.10.2/src/main/java/com/rwtema/extrautils2/backend/entries/XU2Entries.java#L490

Its base class has a "finishedCrafting" that drains the exp, but this is not a valid part of the vanilla interface, in other words, does not exist in standard "IRecipe"
https://github.com/rwtema/Extra-Utilities-2-Source/blob/ff6b75ebc334ee0f1a2c2d1fd1394f8d7e4da0bb/1.10.2/src/main/java/com/rwtema/extrautils2/crafting/EnchantRecipe.java#L48


Possible solution: Fire off the event "ItemCraftedEvent"

**Comment by Lothrazar** [comment]
The other mod appears to be not maintained anymore so this does not seem worth the effort anymore
