### ISSUE TITLE
Duplicate items on server

### ISSUE THREAD

**Issue by TheNoseOfSauron** [Lothrazar/Storage-Network#96]
If you are on a server, if you spam move an item into your storage system, the item will duplicate. This is harder to do if you have a good connection to the server, but the laggier the connection, the faster you can duplicate.

**Comment by PrinceOfAmber** [comment]
When you say spam-move. what does that mena?  Is it shift-clicking them in from your inventory into the GUI? ?

**Comment by TheGreatEye** [comment]
I experienced the issue when simply clicking on the item in my inventory, moving it above the Gui, then spam clicking until it went in.

**Comment by Lothrazar** [comment]
much changes in new versions, this appears solved.  New issues always welcome https://minecraft.curseforge.com/projects/simple-storage-network/files/2659393
